// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "Board_of_issuses/internal/core/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTasksRepository is a mock of TasksRepository interface.
type MockTasksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTasksRepositoryMockRecorder
	isgomock struct{}
}

// MockTasksRepositoryMockRecorder is the mock recorder for MockTasksRepository.
type MockTasksRepositoryMockRecorder struct {
	mock *MockTasksRepository
}

// NewMockTasksRepository creates a new mock instance.
func NewMockTasksRepository(ctrl *gomock.Controller) *MockTasksRepository {
	mock := &MockTasksRepository{ctrl: ctrl}
	mock.recorder = &MockTasksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksRepository) EXPECT() *MockTasksRepositoryMockRecorder {
	return m.recorder
}

// CompleteTask mocks base method.
func (m *MockTasksRepository) CompleteTask(ctx context.Context, userID, taskID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTask", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteTask indicates an expected call of CompleteTask.
func (mr *MockTasksRepositoryMockRecorder) CompleteTask(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTask", reflect.TypeOf((*MockTasksRepository)(nil).CompleteTask), ctx, userID, taskID)
}

// CreateTask mocks base method.
func (m *MockTasksRepository) CreateTask(ctx context.Context, task *domain.Task) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTasksRepositoryMockRecorder) CreateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTasksRepository)(nil).CreateTask), ctx, task)
}

// DeleteTask mocks base method.
func (m *MockTasksRepository) DeleteTask(ctx context.Context, taskID, authorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, taskID, authorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTasksRepositoryMockRecorder) DeleteTask(ctx, taskID, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTasksRepository)(nil).DeleteTask), ctx, taskID, authorID)
}

// GetTaskByID mocks base method.
func (m *MockTasksRepository) GetTaskByID(ctx context.Context, taskID, userID uuid.UUID) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, taskID, userID)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockTasksRepositoryMockRecorder) GetTaskByID(ctx, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockTasksRepository)(nil).GetTaskByID), ctx, taskID, userID)
}

// GetTasksFromOneDesk mocks base method.
func (m *MockTasksRepository) GetTasksFromOneDesk(ctx context.Context, filter *domain.TaskFilter) ([]*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksFromOneDesk", ctx, filter)
	ret0, _ := ret[0].([]*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksFromOneDesk indicates an expected call of GetTasksFromOneDesk.
func (mr *MockTasksRepositoryMockRecorder) GetTasksFromOneDesk(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksFromOneDesk", reflect.TypeOf((*MockTasksRepository)(nil).GetTasksFromOneDesk), ctx, filter)
}

// UpdateTask mocks base method.
func (m *MockTasksRepository) UpdateTask(ctx context.Context, updateData *domain.UpdateTask) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, updateData)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTasksRepositoryMockRecorder) UpdateTask(ctx, updateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTasksRepository)(nil).UpdateTask), ctx, updateData)
}
