// Code generated by MockGen. DO NOT EDIT.
// Source: Board_of_issuses/internal/features/transport/http/handlers (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_user.go -package=mocks . Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domains "Board_of_issuses/internal/core/domains"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Authorization mocks base method.
func (m *MockService) Authorization(ctx context.Context, user *domains.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorization", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorization indicates an expected call of Authorization.
func (mr *MockServiceMockRecorder) Authorization(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorization", reflect.TypeOf((*MockService)(nil).Authorization), ctx, user)
}

// ChangeDeskName mocks base method.
func (m *MockService) ChangeDeskName(ctx context.Context, name string, deskId, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeDeskName", ctx, name, deskId, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeDeskName indicates an expected call of ChangeDeskName.
func (mr *MockServiceMockRecorder) ChangeDeskName(ctx, name, deskId, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeDeskName", reflect.TypeOf((*MockService)(nil).ChangeDeskName), ctx, name, deskId, userID)
}

// ChangeDeskOwner mocks base method.
func (m *MockService) ChangeDeskOwner(ctx context.Context, deskId, userID, newOwner int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeDeskOwner", ctx, deskId, userID, newOwner)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeDeskOwner indicates an expected call of ChangeDeskOwner.
func (mr *MockServiceMockRecorder) ChangeDeskOwner(ctx, deskId, userID, newOwner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeDeskOwner", reflect.TypeOf((*MockService)(nil).ChangeDeskOwner), ctx, deskId, userID, newOwner)
}

// ChangeDeskPassword mocks base method.
func (m *MockService) ChangeDeskPassword(ctx context.Context, password string, deskId, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeDeskPassword", ctx, password, deskId, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeDeskPassword indicates an expected call of ChangeDeskPassword.
func (mr *MockServiceMockRecorder) ChangeDeskPassword(ctx, password, deskId, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeDeskPassword", reflect.TypeOf((*MockService)(nil).ChangeDeskPassword), ctx, password, deskId, userID)
}

// ChangeTaskDescription mocks base method.
func (m *MockService) ChangeTaskDescription(ctx context.Context, userID, taskID int, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeTaskDescription", ctx, userID, taskID, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeTaskDescription indicates an expected call of ChangeTaskDescription.
func (mr *MockServiceMockRecorder) ChangeTaskDescription(ctx, userID, taskID, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeTaskDescription", reflect.TypeOf((*MockService)(nil).ChangeTaskDescription), ctx, userID, taskID, description)
}

// ChangeUserEmail mocks base method.
func (m *MockService) ChangeUserEmail(ctx context.Context, email string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserEmail", ctx, email, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeUserEmail indicates an expected call of ChangeUserEmail.
func (mr *MockServiceMockRecorder) ChangeUserEmail(ctx, email, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserEmail", reflect.TypeOf((*MockService)(nil).ChangeUserEmail), ctx, email, userID)
}

// ChangeUserName mocks base method.
func (m *MockService) ChangeUserName(ctx context.Context, name string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserName", ctx, name, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeUserName indicates an expected call of ChangeUserName.
func (mr *MockServiceMockRecorder) ChangeUserName(ctx, name, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserName", reflect.TypeOf((*MockService)(nil).ChangeUserName), ctx, name, userID)
}

// ChangeUserPassword mocks base method.
func (m *MockService) ChangeUserPassword(ctx context.Context, password string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserPassword", ctx, password, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeUserPassword indicates an expected call of ChangeUserPassword.
func (mr *MockServiceMockRecorder) ChangeUserPassword(ctx, password, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserPassword", reflect.TypeOf((*MockService)(nil).ChangeUserPassword), ctx, password, userID)
}

// ComplyteTask mocks base method.
func (m *MockService) ComplyteTask(ctx context.Context, userID, taskID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComplyteTask", ctx, userID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ComplyteTask indicates an expected call of ComplyteTask.
func (mr *MockServiceMockRecorder) ComplyteTask(ctx, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComplyteTask", reflect.TypeOf((*MockService)(nil).ComplyteTask), ctx, userID, taskID)
}

// ConnectUserToDesk mocks base method.
func (m *MockService) ConnectUserToDesk(ctx context.Context, userID, deskID int, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectUserToDesk", ctx, userID, deskID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectUserToDesk indicates an expected call of ConnectUserToDesk.
func (mr *MockServiceMockRecorder) ConnectUserToDesk(ctx, userID, deskID, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectUserToDesk", reflect.TypeOf((*MockService)(nil).ConnectUserToDesk), ctx, userID, deskID, password)
}

// CreateDesk mocks base method.
func (m *MockService) CreateDesk(ctx context.Context, desk *domains.Desk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDesk", ctx, desk)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDesk indicates an expected call of CreateDesk.
func (mr *MockServiceMockRecorder) CreateDesk(ctx, desk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDesk", reflect.TypeOf((*MockService)(nil).CreateDesk), ctx, desk)
}

// CreateTask mocks base method.
func (m *MockService) CreateTask(ctx context.Context, task *domains.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockServiceMockRecorder) CreateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockService)(nil).CreateTask), ctx, task)
}

// DeleteDesk mocks base method.
func (m *MockService) DeleteDesk(ctx context.Context, deskId, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDesk", ctx, deskId, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDesk indicates an expected call of DeleteDesk.
func (mr *MockServiceMockRecorder) DeleteDesk(ctx, deskId, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDesk", reflect.TypeOf((*MockService)(nil).DeleteDesk), ctx, deskId, userID)
}

// DeleteTask mocks base method.
func (m *MockService) DeleteTask(ctx context.Context, taskID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, taskID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockServiceMockRecorder) DeleteTask(ctx, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockService)(nil).DeleteTask), ctx, taskID, userID)
}

// GetAllDesks mocks base method.
func (m *MockService) GetAllDesks(ctx context.Context, userID int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDesks", ctx, userID)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDesks indicates an expected call of GetAllDesks.
func (mr *MockServiceMockRecorder) GetAllDesks(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDesks", reflect.TypeOf((*MockService)(nil).GetAllDesks), ctx, userID)
}

// GetAllTasks mocks base method.
func (m *MockService) GetAllTasks(ctx context.Context, userId, deskID int) ([]domains.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTasks", ctx, userId, deskID)
	ret0, _ := ret[0].([]domains.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTasks indicates an expected call of GetAllTasks.
func (mr *MockServiceMockRecorder) GetAllTasks(ctx, userId, deskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTasks", reflect.TypeOf((*MockService)(nil).GetAllTasks), ctx, userId, deskID)
}

// GetTasksWithParams mocks base method.
func (m *MockService) GetTasksWithParams(ctx context.Context, userId, deskID int, done bool) ([]domains.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksWithParams", ctx, userId, deskID, done)
	ret0, _ := ret[0].([]domains.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksWithParams indicates an expected call of GetTasksWithParams.
func (mr *MockServiceMockRecorder) GetTasksWithParams(ctx, userId, deskID, done any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksWithParams", reflect.TypeOf((*MockService)(nil).GetTasksWithParams), ctx, userId, deskID, done)
}

// Registration mocks base method.
func (m *MockService) Registration(ctx context.Context, user *domains.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Registration", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Registration indicates an expected call of Registration.
func (mr *MockServiceMockRecorder) Registration(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Registration", reflect.TypeOf((*MockService)(nil).Registration), ctx, user)
}

// UpdateTaskTime mocks base method.
func (m *MockService) UpdateTaskTime(ctx context.Context, userID, taskID, userTime int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskTime", ctx, userID, taskID, userTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskTime indicates an expected call of UpdateTaskTime.
func (mr *MockServiceMockRecorder) UpdateTaskTime(ctx, userID, taskID, userTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskTime", reflect.TypeOf((*MockService)(nil).UpdateTaskTime), ctx, userID, taskID, userTime)
}
